spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      # create / create-drop / update / validate none
      # ???? ?? ??? ?? ?? x
      # ddl-auto: ?? ?? ???? ???? ??? ???? ??? db? ????? ??
      ddl-auto: create-drop
#      format_sql: true
      # ??? ???? ? ??? ???? ???? ????? ? ??? ???? ??? postgresql ???? ?? ???? ???? ??? ????? ?? ?? ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      # ????? sql?? ??? ?, postgresql? ??? sql? ??? ? ??? ??? ??
      hibernate-dialect: org.hibernate.dialect.PostgresSQLDialect
  datasource:
    # ?? db ?? ??
    url: jdbc:postgresql://localhost:5432/board-db
    username: board-master
    password: greenday32
  security:
    user:
      name: board-admin
      password: board-admin-password

# ?? ?? ?? : TRACE < DEBUG < INFO(??) < WARN < ERROR
logging:
  level:
    root: INFO # ?? ?? ??
#    com.example.board.controller.PostController: INFO

#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.engine.transaction.internal.transactionImpl: DEBUG
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG



